name: Security

description: Executes Security Actions
inputs:
  working_dir:
    description: 'Working directory for the action'
    required: true

runs:
  using: "composite"
  steps:
    - uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_NOTIFY_USER_LIST: ${{ env.GITLEAKS_NOTIFY_USER_LIST }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Test with Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ inputs.working_dir }}
        framework: terraform
        skip_check: CKV_TF_1