---
- name: Converge
  hosts: all
  become: true
  vars:
    # Define default variables that your role needs
    wireguard_port: 51820
    wireguard_interface: wg0
    wireguard_address: "192.168.145.1/24"
    wireguard_tunnel_subnet: "192.168.145.0/24"
    wireguard_peer1: "192.168.145.2/32"
    wireguard_private_key_path: "/tmp/wireguard/privatekey"
    wireguard_public_key_path: "/tmp/wireguard/publickey"
    wireguard_config_path: "/tmp/wireguard/wg0.conf"
    user_name: "testuser"
    user_id: 1000
    group_id: 1000
    repo_url: "https://github.com/willquill/vps-proxy.git"
    repo_dest: "/tmp/vps-proxy"
    traefik_username: "testuser"
    traefik_password: "testpass"
    acme_email: "test@example.com"
    public_hostname: "example.com"
    admin_ip_range: "192.168.1.0/24"
    authentik_postgresql_name: "authentik"
    authentik_postgresql_password: "testpass"
    authentik_postgresql_user: "authentik"
    authentik_secret_key: "testsecret"
    cf_dns_api_token: "testtoken"
    cf_zone_api_token: "testtoken"
    timezone: "UTC"
  pre_tasks:
    # Create directories that might be needed
    - name: Ensure /tmp/wireguard directory exists
      ansible.builtin.file:
        path: /tmp/wireguard
        state: directory
        mode: '0755'
  tasks:
    - name: "Include deploy role"
      ansible.builtin.include_role:
        name: "deploy"
