---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-debian13-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  ansible_args:
    - "--timeout=60"
    - "-vvv"
  config_file: ${MOLECULE_SCENARIO_DIRECTORY}/ansible.cfg
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_REMOTE_TMP: /tmp/ansible-tmp
    ANSIBLE_LOCAL_TEMP: /tmp/ansible-tmp
verifier:
  name: ansible
