---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-debian13-ansible:latest"
    command: ""
    # both cgroupns_mode and making /sys/fs/cgroup rw is required when using Ubunt in GitHub Actions
    # This lets the container access the host's cgroup namespace
    # (container shares the host cgroups)
    # https://github.com/ansible/molecule/issues/3094#issuecomment-2198763110
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  ansible_args:
    - "--timeout=60"
    - "-vvv"
  config_file: ${MOLECULE_SCENARIO_DIRECTORY}/ansible.cfg
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_REMOTE_TMP: /tmp/ansible-tmp
    ANSIBLE_LOCAL_TEMP: /tmp/ansible-tmp
verifier:
  name: ansible
