---
# Repository and app setup tasks

- name: Ensure repository directory exists with correct ownership
  file:
    path: "{{ repo_dest }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'

- name: Clone repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    update: yes
  become: true
  become_user: "{{ user_name }}"

- name: Create .env file from template
  template:
    src: env.j2
    dest: "{{ repo_dest }}/.env"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0600'
  vars:
    authentik_postgresql_name: "{{ authentik_postgresql_name }}"
    authentik_postgresql_password: "{{ authentik_postgresql_password }}"
    authentik_postgresql_user: "{{ authentik_postgresql_user }}"
    authentik_secret_key: "{{ authentik_secret_key }}"
    cf_dns_api_token: "{{ cf_dns_api_token }}"
    cf_zone_api_token: "{{ cf_zone_api_token }}"
    traefik_username: "{{ traefik_username }}"
    traefik_password: "{{ traefik_password }}"
    public_hostname: "{{ public_hostname }}"
    timezone: "{{ timezone | default('UTC') }}"

- name: Run docker compose
  command: "docker compose up -d"
  args:
    chdir: "{{ repo_dest }}"
  become: true
  become_user: "{{ user_name }}"
