---
# Docker setup tasks
- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
    mode: '0644'

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_distribution_release }}"
    components: stable
    signed_by: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: docker
    append: yes

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started

- name: Create docker network if it doesn't exist
  ansible.builtin.command: docker network create proxy
  register: create_network_result
  failed_when:
    - create_network_result.rc != 0
    - "'already exists' not in create_network_result.stderr"
