---
# System setup tasks

- name: Update apt cache and upgrade system
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

- name: Install desired packages
  ansible.builtin.apt:
    name:
      - git
      - vim
      - tree
      - curl
      - wget
    state: present

- name: Configure UFW - allow required ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: '22', proto: 'tcp' }
    - { port: '80', proto: 'tcp' }
    - { port: '443', proto: 'tcp' }
    - { port: '636', proto: 'tcp' }
    - { port: '51820', proto: 'udp' }

- name: Enable UFW
  community.general.ufw:
    state: enabled
