---
# Ansible Galaxy requirements file
# Install using: ansible-galaxy install -r galaxy-requirements.yml

collections:
  # # Core Ansible collections
  # - name: ansible.builtin
  #   version: ">=2.16.14"
  
  # Used for sysctl module in wireguard.yml
  - name: ansible.posix
    version: ">=2.1.0"

  - name: community.docker
    version: ">=4.8.1"
  
  - name: community.general
    version: ">=11.4.0"

  # # Useful for network configurations, firewalls, etc
  # - name: ansible.netcommon
  #   version: ">=7.2.0"
