name: Documentation Checks

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
      - ".markdownlint.json"
      - ".markdownlintignore"
      - ".github/workflows/docs.yml"
  # Allows manual triggering
  workflow_dispatch:

jobs:
  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y nodejs npm git
      - name: Install markdownlint
        run: |
          npm install -g markdownlint-cli
      - name: Run markdownlint
        run: |
          markdownlint --config .markdownlint.json --ignore LICENSE.md --ignore-path .markdownlintignore *.md
