name: OpenTofu

on:
  # Allows manual triggering
  workflow_dispatch:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # AWS keys for S3 state backend
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # To populate Terraform variables
  TF_VAR_repo_owner: ${{ github.repository_owner }}
  TF_VAR_ssh_authorized_key: ${{ secrets.VPS_PROXY_KEY }}

jobs:
  tofu-lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: v1.10.5
            working_dir: opentofu
          - version: v1.10.5
            working_dir: tfstate
    environment: hetzner-cloud
    env:
      tf_actions_working_dir: ${{ matrix.working_dir }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.version }}--${{ matrix.working_dir }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - name: tofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true

      - uses: ./.github/actions/opentofu-setup

      - name: tofu Validate
        id: validate
        run: tofu validate

  tofu-plan:
    name: OpenTofu Plan
    needs: tofu-lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: opentofu
            version: v1.10.5
            working_dir: opentofu
          - tool: opentofu
            version: v1.10.5
            working_dir: tfstate
    environment: hetzner-cloud
    env:
      tf_actions_working_dir: ${{ matrix.working_dir }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.tool }}-${{ matrix.version }}--${{ matrix.working_dir }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/opentofu
        with:
          plan: "true"

  # Disabled for now because I lint locally
  #   ansible-lint:
  #     name: Ansible Lint
  #     runs-on: ubuntu-24.04
  #     steps:
  #       - uses: actions/checkout@v5
  #       - name: Run ansible-lint
  #         uses: ansible/ansible-lint@main # or vX.X.X version
  #         # optional (see below):
  #         with:
  #           args: ""
  #           #gh_action_ref: "<version - e.g. `v25.5.0`>" # Not recommended for non-composite action use
  #           setup_python: "true"
  #           working_directory: ""
  #           requirements_file: ""

  #   yaml-lint:
  #     name: Yaml Lint
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v5
  #       - name: yaml-lint
  #         uses: ibiqlik/action-yamllint@v3
  #       - run: echo ${{ steps.yaml-lint.outputs.logfile }}
  #       - uses: actions/upload-artifact@v4
  #         if: always()
  #         with:
  #           name: yamllint-logfile
  #           path: ${{ steps.yaml-lint.outputs.logfile }}
