name: Lint & Plan

on:
  # Allows manual triggering
  workflow_dispatch:
  pull_request:

env:
  TZ: ${{ secrets.TZ }}
  # AWS keys for S3 state backend
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # To populate Terraform variables
  TF_VAR_repo_owner: ${{ github.repository_owner }}
  TF_VAR_workflow_actor: ${{ github.actor }}
  TF_VAR_ssh_authorized_key: ${{ secrets.VPS_PROXY_KEY }}
  # Hetzner Cloud token required to create resources
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

jobs:
  # FIXME: Duplicated in nightly, turn into Workflow
  security-git-leaks:
    name: Gitleaks Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          # This provides full history for accurate scanning
          fetch-depth: 0
      - uses: ./.github/actions/security
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitleaks_notify_user_list: ${{ github.repository_owner }}

  security-tfsec:
    name: Tfsec Scan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - working_dir: opentofu
          - working_dir: tfstate

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.working_dir }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/security
        with:
          working_dir: ${{ matrix.working_dir }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitleaks_notify_user_list: ${{ github.repository_owner }}

  tofu-lint:
    needs: security-tfsec
    runs-on: ubuntu-latest
    environment: hetzner-cloud
    strategy:
      fail-fast: false
      matrix:
        include:
          - tofu_version: "~>1.10.6"
            working_dir: opentofu
          - tofu_version: "~>1.10.6"
            working_dir: tfstate

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.working_dir }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/opentofu
        with:
          tofu_version: ${{ matrix.tofu_version }}
          working_dir: ${{ matrix.working_dir }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          event_name: ${{ github.event_name }}
          lint: "true"

  tofu-plan:
    needs: security-tfsec
    runs-on: ubuntu-latest
    environment: hetzner-cloud
    strategy:
      fail-fast: false
      matrix:
        include:
          - tofu_version: "~>1.10.6"
            working_dir: opentofu

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.working_dir }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/opentofu
        with:
          tofu_version: ${{ matrix.tofu_version }}
          working_dir: ${{ matrix.working_dir }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          event_name: ${{ github.event_name }}
          plan: "true"
