name: Security Scan

on:
  # Allows manual triggering
  workflow_dispatch:
  push:
  # Run on a schedule to catch new vulnerabilities
  schedule:
    - cron: "0 4 * * *" # 4 AM every day

jobs:
  detect-secrets:
    name: Detect Secrets with Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_NOTIFY_USER_LIST: ${{ github.repository_owner }}

  checkov:
    uses: ./.github/workflows/checkov.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: v1.10.5
            working_dir: opentofu
          - version: v1.10.5
            working_dir: tfstate
    with:
      directory: ${{ matrix.working_dir }}
