name: Security Scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  # Run on a schedule to catch new vulnerabilities
  schedule:
    - cron: "0 4 * * 1" # 4 AM every Monday
  # Allows manual triggering
  workflow_dispatch:

jobs:
  detect-secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git wget
      - name: Install Gitleaks
        run: |
          wget -q https://github.com/zricethezav/gitleaks/releases/download/v8.18.3/gitleaks_8.18.3_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.3_linux_x64.tar.gz
          chmod +x gitleaks
          mv gitleaks /usr/local/bin/
      - name: Detect secrets in repo
        run: |
          gitleaks detect -v

  trivy-scan:
    name: Vulnerability Scanning
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y wget apt-transport-https gnupg lsb-release
      - name: Setup Trivy
        run: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | tee -a /etc/apt/sources.list.d/trivy.list
          apt-get update
          apt-get install -y trivy
      - name: Run Trivy vulnerability scanner
        run: |
          trivy fs --exit-code 1 --no-progress --ignore-unfixed --severity CRITICAL,HIGH .
