name: Security Scan

on:
  # Allows manual triggering
  workflow_dispatch:
  push:
  # Run on a schedule to catch new vulnerabilities
  schedule:
    - cron: "0 4 * * *" # 4 AM every day

jobs:
  detect-secrets:
    name: Detect Secrets with Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_NOTIFY_USER_LIST: ${{ github.repository_owner }}

  checkov-tfstate:
    uses: ./.github/workflows/checkov.yml
    with:
      directory: terraform/tfstate

  checkov-terraform:
    uses: ./.github/workflows/checkov.yml
    with:
      directory: terraform
