name: Security Scan

on:
  # Allows manual triggering
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  # Run on a schedule to catch new vulnerabilities
  schedule:
    - cron: "0 4 * * *" # 4 AM every day

jobs:
  detect-secrets:
    name: Detect Secrets with Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
