name: Update

on:
  # Manual trigger
  workflow_dispatch:

jobs:
  ansible-deploy:
    name: Ansible Update
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
    environment: hetzner-cloud
    # Note: We do not need to set each env because instead of envvars,
    #       we set -e options where necessary
    env:
      ANSIBLE_VERSION: ${{ github.event.inputs.version || '9.3.0' }}
      ANSIBLE_HOST_KEY_CHECKING: False
      ANSIBLE_FORCE_COLOR: 1

    steps:
      # ---------- Checkout code ----------
      - name: Checkout repo
        uses: actions/checkout@v5

      # ---------- Setup tooling ----------
      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: "Cache python packages"
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ env.ANSIBLE_VERSION }}

      - name: "Install packages"
        shell: bash
        run: |
          python -m pip install ansible==${{ env.ANSIBLE_VERSION }}
      - name: "Print Ansible version"
        run: ansible-playbook --version

      # ---------- Install Ansible Galaxy requirements ----------
      - name: Install Ansible Galaxy requirements
        run: |
          ansible-galaxy collection install -r ansible/galaxy-requirements.yml

      # Get values from Terraform output
      - name: Download Terraform output
        uses: actions/download-artifact@v5
        with:
          name: tf-output

      - name: Parse SERVER_IPV4 from output
        id: parse_output
        run: |
          SERVER_IPV4=$(jq -r '.server_ipv4.value' tf_output.json)
          echo "SERVER_IPV4=$SERVER_IPV4" >> $GITHUB_ENV

      # ---------- SSH key ----------
      # Use IPv4 from Terraform output
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PROXY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 2222 -H ${{ env.SERVER_IPV4 }} >> ~/.ssh/known_hosts

      # ---------- Create inventory file ----------
      - name: Create inventory file
        run: |
          cat <<EOF > inventory
          [vps]
            ${{ env.SERVER_IPV4 }} ansible_user=${{ github.repository_owner }} ansible_port=2222
          EOF

      # ---------- Run Ansible Check----------
      # FIXME: admin_ip_range not used in playbook. Why did I add this again?
      - name: Run ansible playbook with check option
        id: ansible-check
        run: |
          ansible-playbook \
            -i inventory \
            --check \
            -e "ansible_ssh_private_key_file=~/.ssh/id_ed25519" \
            ansible/main.yml --tags update

      # ---------- Run Ansible ----------
      - name: Run ansible playbook
        # Only run if every previous step succeeded
        if: ${{ success() }}
        run: |
          ansible-playbook \
            -i inventory \
            -e "ansible_ssh_private_key_file=~/.ssh/id_ed25519" \
            ansible/main.yml --tags update
